### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by bpstewar** [worldbank/GOSTnets#1]
We need to create documentation - look into ReadTheDocs

**Comment by d3netxer** [comment]
we finally got something: https://gostnets.readthedocs.io/en/latest/GOSTnets.html

I was having a lot of trouble debugging as the build kept on failing, it turns out the the .readthedocs.yml configuration file was pointing the **wrong** path of the conf.py file.

I still need to learn a lot more how sphinx works.

**Comment by d3netxer** [comment]
Ok docs are working better now. 

If we decide later we want to go with docstrings in Google or NumPy format, we can look into pyment (https://github.com/dadadel/pyment/) to see if we can auto translate all of the docstrings. Then we would test enabling the Napoleon extension within Sphinx.
