### ISSUE TITLE
Remove the src/ directory?

### ISSUE THREAD

**Issue by elbeejay** [worldbank/GOSTnets#55]
@g4brielvs wanted to ask about this - why do we nest the `GOSTnets` directory within `src`? 

Was just noticing locally that my builds from `pyproject.toml` automatically create a `GOSTnets` subdirectory within the root repository and that's where the autogenerated `_version.py` file is placed, which makes me think the pyproject setup is expecting the `GOSTnets` directory to sit directly beneath the repo root.

**Comment by g4brielvs** [comment]
@elbeejay Thank you for bringing up thi point regarding the structure of our project and the placement of the [GOSTnets](https://github.com/worldbank/GOStnets) directory within a `src` directory. The decision to nest the [GOSTnets](https://github.com/worldbank/GOStnets) directory within `src` is indeed intentional and aligns with several (opiniated) best practices in Python project development. 

A [discussion thread has been created](https://github.com/orgs/worldbank/discussions/11) to engage the community on this and I'm eager to hear your thoughts.
